### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by chevett** [JamesMGreene/Function.name#2]
Would you accept a PR for a package.json and publish this to npm?  If so, I'll send it right over.

**Comment by JamesMGreene** [comment]
Thanks for the idea. Now available: https://www.npmjs.com/package/function.name-polyfill

Also note that someone else released a very similar module as well: https://www.npmjs.com/package/function.name

**Comment by JamesMGreene** [comment]
Closed via a10f338f4b1638f2ad001d0adfb3d45d29819615.

**Comment by chevett** [comment]
Thank you!
