### ISSUE TITLE
Submit to polyfill.io

### ISSUE THREAD

**Issue by Regaddi** [JamesMGreene/Function.name#3]
Hi @JamesMGreene,

have you considered to submit this Polyfill to https://github.com/Financial-Times/polyfill-service?
I'd love to see it available there!

Best,
Chris

**Comment by Regaddi** [comment]
There's a pending issue at https://github.com/Financial-Times/polyfill-service/issues/943

**Comment by JamesMGreene** [comment]
Will do, hopefully tonight.

**Comment by JamesMGreene** [comment]
PR submitted to Polyfill: https://github.com/Financial-Times/polyfill-service/pull/951

Thanks!
